Drill4J/admin-ui

src/pages/login-page/login-page.tsx
fix misspell at continue as a guest button
change instructions text at login page
Issue: US1.1
=> US1.1: fix misspell at continue as a guest button, change instructions text at login page

src/components/sidebar/sidebar.module.scss, src/components/sidebar/sidebar.tsx, src/pages/settings-page/settings-page.tsx
fix setting page text
added onClick to sidebar logo
Issue: US6.1_FE
=> US6.1: fix setting page text, added onClick to sidebar logo

nginx/nginx.conf, src/common/connection/ws-connection.ts, src/common/constants/connection.ts
change WebSocket URL from /api/ to /ws/, added WebSocket config to nginx
=> change WebSocket URL from /api/ to /ws/, added WebSocket config to nginx

src/components/modal/modal.tsx, src/components/modal/portal.tsx, src/components/sidebar/sidebar.tsx, src/pages/agent-info-page/add-plugins-modal/add-plugins-modal.tsx, src/pages/agent-info-page/agent-info-page.tsx, src/pages/agent-info-page/agent-plugins-table/agent-plugins-table.tsx, src/pages/agents-page/agents-page.tsx, src/pages/agents-page/card-view/agent-card/agent-card.tsx, src/pages/agents-page/card-view/card-view.tsx, src/pages/agents-page/get-selected-agents-actions.ts, src/pages/agents-page/table-view/table-view.tsx, src/types/agent.ts, src/types/plugin.ts
added typescript typings;
refactor modal portal;
=> added typescript typings, refactor modal portal

src/pages/agent-info-page/add-plugins-modal/add-plugins-modal.tsx
=> US3.3: switch plugin library from stub to integration

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-column/associated-test-column.tsx
=> B23: fix issue when user can open associated tests modal without tests

src/pages/agents-page/card-view/agent-card/agent-card.tsx
=> D4J-40: fix agent-card actions

src/pages/agent-full-page/agent-full-page.module.scss, src/pages/agent-full-page/agent-full-page.tsx
=> DJ4-55: fix agent full page header

src/components/icon/declare-icon.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.module.scss, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/index.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/types/coverage.ts
=> D4J-31: added increase/decrease coverage arrow

src/components/overflow-text/overflow-text.module.scss
=> D4J-3: overflow-text is reworked, added support colors

src/pages/agent-full-page/coverage-plugin/use-build-version.ts
=> D4J-70: fix use-build-version don't subscribe if no buildVersion

src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/types/method-coverage.ts
=> D4J-39: change method description from descriptor to formated signature

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/new-methods-modal/index.ts, src/pages/agent-full-page/coverage-plugin/new-methods-modal/new-methods-modal.module.scss, src/pages/agent-full-page/coverage-plugin/new-methods-modal/new-methods-modal.tsx, src/types/new-method.ts
=> D4J-61: new methods modal

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.module.scss
=> D4J-66: fix associated-test-modal test icon align

src/pages/agent-full-page/coverage-plugin/coverage-plugin.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx
=> D4J-72: added text-decoration to NewMethod

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss
=> D4J-38: remove opacity from item-info

src/pages/agents-page/card-view/agent-card/agent-card.module.scss, src/pages/agents-page/card-view/agent-card/agent-card.tsx, src/pages/agents-page/card-view/card-view.tsx
=> D4J-41: added disabled modifier to agent-card

src/components/button/button.module.scss, src/pages/agent-info-page/add-plugins-modal/add-plugins-modal.module.scss, src/pages/agent-info-page/add-plugins-modal/add-plugins-modal.tsx
=> D4J-42: disable add plugin button if no plugin selected

src/components/table-checkbox/table-checkbox.module.scss, src/components/table-checkbox/table-checkbox.tsx, src/components/table/expanded-row-content.tsx, src/components/table/selectable-table.tsx, src/components/table/table.module.scss, src/components/table/table.tsx, src/components/table/table__row.tsx, src/pages/agents-page/table-view/table-view.tsx
=> D4J-43: added highlight to selected row

src/components/message-panel/message-panel.module.scss, src/components/tabs/tabs.module.scss, src/pages/agent-full-page/coverage-plugin/card/card.module.scss
=> D4J-80: remove font-weight property

src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agents-page/card-view/agent-card/agent-card.tsx
=> D4J-87: display covered new methods count, change icon at card view

src/components/index.ts, src/components/spinner/index.ts, src/components/spinner/spinner.module.scss, src/components/spinner/spinner.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.module.scss, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/types/collection-state.ts
=> D4J-88: added spinner while gathering tests coverage

src/components/badge/badge.module.scss, src/components/badge/badge.tsx, src/components/toolbar/toolbar.module.scss, src/components/toolbar/toolbar.tsx, src/pages/agent-full-page/agent-full-page.module.scss, src/pages/agent-full-page/agent-full-page.tsx
=> D4J-101: agent-full-page toolbar re-design

nginx/nginx.conf
=> D4J-113: fix nginx config from const value to docker-network

src/components/popup/popup.module.scss, src/components/popup/popup.tsx, src/pages/agent-settings-page/agent-settings-page.module.scss, src/pages/agent-settings-page/agent-settings-page.tsx, src/pages/agent-settings-page/unregister-agent-modal/index.ts, src/pages/agent-settings-page/unregister-agent-modal/unregister-agent-modal.module.scss, src/pages/agent-settings-page/unregister-agent-modal/unregister-agent-modal.tsx
=> EPMDJ-35: added unregister agent modal

src/pages/agents-page/register-agent-modal/register-agent-modal.tsx, src/types/agent-registration-info.ts
=> EPMDJ-32: remove buildVersion and id from register agent request

src/components/popup/popup.tsx
=> EPMDJ-188: change closeOnClick default parameter to false

src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDJ-186: added default value to agent name at registration modal

src/pages/agent-settings-page/agent-settings-page.tsx
=> EPMDJ-102: remove buildVersionAlias from update agent settings POST

src/forms/form-validators.spec.ts, src/forms/form-validators.ts, src/pages/agent-settings-page/agent-settings-page.tsx, src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDJ-225: added validation to agent group

src/pages/agent-full-page/agent-full-page.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/types/agent.ts
=> EPMDJ-233: fix build verisons dropdown at coverage-plugin

src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDJ-234: fix buildAlias validation

src/components/table/selectable-table.tsx, src/pages/agents-page/table-view/table-view.tsx
=> EPMDJ-187: remove ability to select unregister agent

src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx
=> EPMDJ-376: added display build id if no alias provided

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-723: fix validation at scope-name field

src/components/table/expandable-table/row-expander/row-expander.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/coverages-by-type/coverages-by-type.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agents-page/layout-switch/layout-switch.tsx
=> EPMDJ-915: added sorting to scopes list, fix warning at console

src/forms/inputs/checkbox/checkbox.module.scss, src/forms/inputs/checkbox/checkbox.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/active-sessions-panel/active-sessions-panel.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/active-sessions-panel/active-sessions-panel.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/active-sessions-panel/index.ts, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/finish-scope-modal.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/finish-scope-modal/scope-summary/scope-summary.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-979: added warning message if active sessions exists

package.json, src/pages/agent-full-page/coverage-plugin/card/card.module.scss, src/pages/agent-full-page/coverage-plugin/card/card.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/dashboard/dashboard.tsx, src/pages/agent-full-page/coverage-plugin/methods-modal/index.ts, src/pages/agent-full-page/coverage-plugin/methods-modal/methods-modal.module.scss, src/pages/agent-full-page/coverage-plugin/methods-modal/methods-modal.tsx, src/pages/agent-full-page/coverage-plugin/new-methods-modal/index.ts, src/pages/agent-full-page/coverage-plugin/project-methods-card/combine-modified-methods.ts, src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.module.scss, src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/types/coverage-by-type.ts, src/types/coverage.ts, src/types/methods-details.ts, src/types/methods-info.ts, src/types/methods.ts, src/types/new-methods-coverage.ts, yarn.lock
=> EPMDJ-1036: added separation between project methods

src/pages/agent-settings-page/agent-settings-form/agent-settings-form.tsx, src/pages/agent-settings-page/agent-settings-page.tsx
=> EPMDJ-824: remove buildVersionAlias field

src/forms/form-validators.ts, src/forms/index.ts, src/forms/inputs/textarea/textarea.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/index.ts, src/pages/plugin-settings-page/index.ts, src/pages/plugin-settings-page/plugin-settings-page.module.scss, src/pages/plugin-settings-page/plugin-settings-page.tsx, src/routes/page-switcher.tsx, src/types/coverage-plugin-config.ts
=> EPMDJ-953: added plugin settings page

src/components/menu/menu.module.scss
=> EPMDJ-1111: fix menu size to auto width

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-1112: change text of rename scope button

src/components/menu/menu.module.scss, src/forms/inputs/dropdown/dropdown.tsx, src/pages/agent-full-page/agent-full-page.tsx, src/pages/agent-full-page/coverage-plugin/covarage-plugin-modals.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/dashboard/dashboard.tsx, src/pages/agent-full-page/coverage-plugin/plugin-header/plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/plugin-header/use-agent-id.ts, src/pages/agent-full-page/coverage-plugin/scope/active-sessions-panel/active-sessions-panel.tsx, src/pages/agent-full-page/coverage-plugin/scope/current-scope/current-scope.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/store/index.ts, src/pages/agent-full-page/coverage-plugin/store/plugin-context.ts, src/pages/agent-full-page/coverage-plugin/store/plugin-state-provider.tsx, src/pages/agent-full-page/coverage-plugin/store/reducer.ts, src/pages/agent-full-page/coverage-plugin/store/store-types.ts, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx, src/pages/agent-full-page/coverage-plugin/use-build-version.ts
=> EPMDJ-1042: added coverage plugin store

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-950: added finished scope badge at scope page

src/components/menu/menu.module.scss, src/components/modal/modal.module.scss, src/components/popup/popup.module.scss
=> EPMDJ-1118: fix z-index of modal and popup fade

src/pages/agents-page/card-view/agent-card/agent-card.module.scss, src/pages/agents-page/table-view/table-view.tsx
=> EPMDJ-439: fix overflow at card view

src/pages/agents-page/card-view/agent-card/agent-card.module.scss, src/pages/agents-page/table-view/table-view.tsx
=> EPMDJ-439: added break-word

src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-1145: fix cancel scope label at menu

src/components/popup/popup.tsx
=> EPMDJ-1148: added stopPropagation to popup fade

src/components/toolbar/toolbar.module.scss, src/components/toolbar/toolbar.tsx, src/pages/agent-info-page/agent-info-page.tsx, src/pages/agent-info-page/agent-plugins-table/agent-plugins-table.tsx
=> EPMDJ-1095: remove unused UI elements

src/components/page-header/page-header.tsx, src/components/table/default-cell.tsx, src/components/table/default-header-cell.tsx, src/components/table/table__header.tsx, src/components/toolbar/toolbar.tsx, src/hooks/index.ts, src/hooks/use-agent.ts, src/hooks/use-click-outside.ts, src/hooks/use-ws-connection.ts, src/pages/agent-full-page/agent-full-page.tsx, src/pages/agent-full-page/coverage-plugin/api/toggle-scope.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/plugin-header/use-agent-id.ts, src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.tsx, src/pages/agent-full-page/coverage-plugin/test-details/no-tests-stub/no-tests-stub.tsx, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/pages/agent-info-page/add-plugins-modal/add-plugins-modal.tsx, src/pages/agent-info-page/agent-info-page.tsx, src/pages/agent-info-page/agent-plugins-table/agent-plugins-table.tsx, src/pages/agent-settings-page/agent-settings-page.tsx, src/pages/plugin-settings-page/plugin-settings-page.tsx, yarn.lock
=> EPMDJ-1167: added redirect to not-found page if agent is not found

src/hooks/use-agent.ts
=> EPMDJ-1167: added redirect to not-found if agent is not registered

src/hooks/use-agent.ts, src/hooks/use-click-outside.ts, src/hooks/use-ws-connection.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx
=> EPMDJ-1430: fix hooks, added temprorary solution

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-timer/index.ts, src/pages/agent-full-page/coverage-plugin/scope/scope-timer/scope-timer.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-timer/scope-timer.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/utils/get-time-difference.ts, src/utils/index.ts
=> EPMDJ-1415: added scope duration

src/common/connection/configure-axios.ts, src/common/connection/default-ws-connection.ts, src/pages/agent-full-page/coverage-plugin/scope/current-scope/current-scope.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-1415: move local development to stage env

src/forms/inputs/toggler/toggler.module.scss, src/pages/agent-info-page/agent-plugins-table/agent-plugins-table.tsx
=> EPMDJ-291: disable on/off plugin toggler

src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-1555: Implement messages about scope including / excluding.

src/pages/agent-settings-page/agent-settings-form/agent-settings-form.tsx
=> EPMDJ-1577: Changed "Select a group" to "Specify a group"

src/pages/agent-settings-page/unregister-agent-modal/unregister-agent-modal.tsx, src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDG-1593: changed message for agent registration and unregister

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx
=> EPMDJ-1594: added disable click at risks and tests to run

src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDJ-1575: change build alias validation from 3,32 to 1,64

src/forms/inputs/dropdown/dropdown.module.scss, src/pages/agent-full-page/coverage-plugin/tests-to-run-modal/tests-to-run-modal.module.scss, src/pages/agent-full-page/coverage-plugin/tests-to-run-modal/tests-to-run-modal.tsx
=> EPMDJ-1609: added copy to clipboard button at tests to run modal

src/pages/agent-full-page/coverage-plugin/code-coverage-card/coverages-by-type/coverages-by-type.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/detailed-code-coverage-card/coverage-distribution/coverage-distribution.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/initial-data-controller.ts, src/pages/agent-full-page/coverage-plugin/scope/active-sessions-panel/active-sessions-panel.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/store/index.ts, src/pages/agent-full-page/coverage-plugin/store/reducer.ts, src/pages/agent-full-page/plugin-header/plugin-header.tsx, src/pages/agent-full-page/store/index.ts, src/pages/agent-full-page/store/plugin-context.ts, src/pages/agent-full-page/store/reducer.ts, src/pages/agent-full-page/store/store-types.ts, src/types/active-sessions.ts, src/types/test-type-summary.ts, src/types/test-types.ts
=> EPMDJ-899: added recoring icon to scopes list, refactor active sessions

src/components/page-header/page-header.module.scss, src/components/page-header/page-header.tsx, src/components/table/table.module.scss, src/hooks/use-element-width.ts, src/pages/agent-full-page/build-list/build-list.module.scss, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.module.scss, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/scope-summary/scope-summary.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss, src/pages/agent-info-page/agent-info-page.tsx, src/utils/date-formatter.ts, src/utils/index.ts
=> EPMDJ-1610: changed the "Build list" page

src/pages/agent-full-page/coverage-plugin/tests-to-run-modal/tests-to-run-modal.tsx
=> EPMDJ-1609: remove special symbols from test to run curl

src/pages/agent-full-page/coverage-plugin/coverage-details/compound-cell/compound-cell.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/compound-cell/compound-cell.tsx
=> EPMDJ-1556: Add overflow text for all fields

src/utils/date-formatter.spec.ts, src/utils/date-formatter.ts
=> EPMDJ-1610: delete ',' between date and time

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-1830: fixed scopes list url

src/components/icon/declare-icon.tsx, src/forms/inputs/button/button.tsx, src/layouts/panel/panel.tsx, src/pages/agent-full-page/breadcrumbs/breadcrumbs.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/coverages-by-type/coverages-by-type.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx, src/pages/agent-full-page/coverage-plugin/methods-modal/methods-modal.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-actions/active-scope-actions.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-info-page/agent-info-page.tsx, src/pages/agent-info-page/agent-plugins-table/agent-plugins-table.tsx, src/pages/agent-settings-page/agent-settings-page.tsx, src/pages/agent-settings-page/general-settings-form/general-settings-form.tsx, src/pages/agent-settings-page/system-setting-form/system-settings-form.tsx, src/pages/agents-page/agent-status-toggler/agent-status-toggler.tsx, src/pages/agents-page/table-view/actions-column/actions-column.tsx, src/pages/agents-page/table-view/name-column/name-column.tsx
=> EPMDJ-1759: Add data-test attributes

src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx
=> EPMDJ-1835: added redirect after delete scope

src/forms/inputs/toggler/toggler.module.scss, src/pages/agent-full-page/build-list/rename-build-version-modal/rename-build-version.ts, src/pages/agent-settings-page/general-settings-form/general-settings-form.tsx, src/pages/agent-settings-page/system-setting-form/system-settings-form.tsx, src/pages/agent-settings-page/unregister-agent-modal/unregister-agent-modal.tsx, src/pages/agents-page/register-agent-modal/register-agent-modal.tsx
=> EPMDJ-1196: Increased transparency and added catch

src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.module.scss, src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.tsx, src/types/methods.ts
=> EPMDJ-1557: Implemented the number of deleted methods

src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-1835: change redirect logic after delete scope aciton

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.tsx
=> EPMDJ-1719: Implement overflow + mouseover func. for long package

src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
=> EPMDJ-1494: fix coverage section value

src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.tsx, src/pages/agent-full-page/dashboard/dashboard.module.scss, src/pages/agent-full-page/dashboard/no-plugins-stub/no-plugins-stub.module.scss, src/pages/agent-full-page/dashboard/plugin-card/plugin-card.module.scss, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/types/methods.ts
=> EPMDJ-1494: change allMethod to allModifiedMethods

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.tsx
=> EPMDJ-1865: fix line-height for accociated modal info pane

src/pages/agent-full-page/dashboard/dashboard.tsx
=> EPMDJ-1867: fix view more link

src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/dashboard/sections/tests-section.tsx, src/types/coverage.ts
=> EPMDJ-1871: change scopesCount to finishedScopesCount

package-lock.json, src/pages/agent-full-page/agent-full-page.tsx
=> EPMDJ-1942: fix new build notification on another agent

src/forms/form-group/form-group.module.scss, src/forms/form-group/form-group.tsx, src/forms/form-validators.spec.ts, src/forms/form-validators.ts, src/forms/inputs/input/input.module.scss, src/pages/agent-full-page/build-list/rename-build-version-modal/rename-build-version-modal.tsx, src/pages/agent-full-page/coverage-plugin/manage-sessions-modal/manage-sessions-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/agent-full-page/new-build-modal/build-alias/build-alias.tsx, src/pages/agent-registration-page/agent-registration-page.module.scss, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/cancel-agent-registration-modal/cancel-agent-registration-modal.module.scss, src/pages/agent-registration-page/general-settings-form/general-settings-form.module.scss, src/pages/agent-registration-page/general-settings-form/general-settings-form.tsx, src/pages/agent-registration-page/install-plugins-step/install-plugins-step.module.scss, src/pages/agent-registration-page/install-plugins-step/install-plugins-step.tsx, src/pages/agent-registration-page/system-setting-form/system-settings-form.module.scss, src/pages/agent-registration-page/system-setting-form/system-settings-form.tsx, src/pages/agent-settings-page/agent-settings-page.module.scss, src/pages/agent-settings-page/general-settings-form/general-settings-form.module.scss, src/pages/agent-settings-page/general-settings-form/general-settings-form.tsx, src/pages/agent-settings-page/plugins-settings/plugins-settings.module.scss, src/pages/agent-settings-page/plugins-settings/plugins-settings.tsx, src/pages/agent-settings-page/system-setting-form/system-settings-form.module.scss, src/pages/agent-settings-page/system-setting-form/system-settings-form.tsx
=> EPMDJ-1958: Fix remarks for wizard

src/components/overflow-text/overflow-text.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-rate-icon/coverage-rate-icon.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-rate-icon/coverage-rate-icon.tsx, src/pages/agent-full-page/coverage-plugin/coverage-rate-icon/index.ts, src/pages/agent-full-page/coverage-plugin/methods-modal/index.ts, src/pages/agent-full-page/coverage-plugin/methods-sidebar/index.ts, src/pages/agent-full-page/coverage-plugin/methods-sidebar/methods-sidebar.module.scss, src/pages/agent-full-page/coverage-plugin/methods-sidebar/methods-sidebar.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.tsx, src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/index.ts, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.tsx, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/index.ts, src/pages/agent-full-page/coverage-plugin/test-details/methods-list/index.ts, src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx, src/pages/agent-full-page/dashboard/single-bar/single-bar.tsx, src/types/method-covered-by-test.ts
=> EPMDJ-1781: added covered methods sidebar

src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-2004: remove actions column from test-details

package-lock.json, package.json, src/components/menu/menu.module.scss, src/components/menu/menu.tsx, yarn.lock
=> EPMDJ-1844: fix menu position if menu not visible

src/pages/agent-full-page/coverage-plugin/initial-data-controller.ts, src/pages/agent-full-page/dashboard/no-plugins-stub/no-plugins-stub.tsx
=> EPMDJ-2017: fix initial data contoroller recursive update bug

src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.tsx, src/types/method-covered-by-test.ts
=> EPMDJ-2044: fix covered methods sidebar

src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
=> EPMDJ-2044: fix label min-width

Dockerfile, nginx/nginx.conf
=> EPMDJ-2048: added docker multi-stage build

src/layouts/plugins-layout/plugins-layout.module.scss
=> EPMDJ-2063: Updated the layout for the chrome version (79.0.3945.88)

src/pages/agent-settings-page/plugins-settings/add-plugins-modal/add-plugins-modal.tsx, src/pages/agent-settings-page/system-setting-form/system-settings-form.tsx
=> EPMDJ-2057: Improved lock/unlock and "Add plugin" operation

src/pages/agent-registration-page/agent-registration-page.module.scss, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/register-agent.ts
=> EPMDJ-2092: Added general message after finished registration agent

src/pages/settings-page/unregister-agent-modal/unregister-agent-modal.tsx
=> EPMDJ-2097: added redirect to agents list after unregister

src/pages/agent-registration-page/register-agent.ts
=> EPDMJ-2125: added imidiate redirect after registration

src/pages/agent-full-page/agent-full-page.tsx, src/pages/agents-page/agents-page.tsx
=> EPMDJ-1886: fix incompatibility of agents-list after service group integration

src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.tsx
=> EPMDJ-2127: Corrected validation message for Service Group Name field

src/components/filled-badge/filled-badge.module.scss, src/components/filled-badge/filled-badge.tsx, src/components/filled-badge/index.ts, src/components/index.ts, src/pages/agents-page/table-view/name-column/name-column.module.scss, src/pages/agents-page/table-view/name-column/name-column.tsx, src/pages/agents-page/table-view/table-view.tsx, src/pages/agents-page/table-view/table/expandable-table/expandable-table.tsx, src/pages/agents-page/table-view/table/expanded-row-content.tsx, src/pages/agents-page/table-view/table/table.module.scss, src/pages/agents-page/table-view/table/table__row.tsx
=> EPMDJ-1886: fix colors at agents-list added agent status

src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx
=> EPMDJ-2140: remove required validation from description field

src/pages/agents-page/table-view/actions-column/actions-column.module.scss, src/pages/agents-page/table-view/actions-column/actions-column.tsx
=> EPMDJ-1886: added new register button

src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.module.scss, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.tsx, src/pages/settings-page/agent-settings/plugins-settings/plugins-settings.tsx
=> EPMDJ-2153: Handled the case when relation = null

src/pages/agents-page/table-view/name-column/name-column.tsx
=> EPMDJ-1886: disable redirect to service group

src/pages/agent-full-page/plugin-header/plugin-header.module.scss, src/pages/agent-full-page/plugin-header/plugin-header.tsx, src/utils/index.ts
=> EPMDJ-2154: Corrected agent status in the header if status = offline

src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/general-settings-form/general-settings-form.tsx, src/pages/agent-registration-page/register-agent.ts, src/pages/agents-page/table-view/table-view.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.module.scss, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/types/agent-registration-info.ts, src/types/common-entity.ts
=> EPMDJ-2106: Change "Group" name to "Environment"

src/pages/agents-page/no-agents-stub/no-agents-stub.module.scss, src/pages/agents-page/no-agents-stub/no-agents-stub.tsx
=> EPMDJ-2156: Added link "this guide" on the empty agents list page

src/pages/agents-page/agents-page.tsx
=> EPMDJ-2158: Corrected agents number on the agents list page

src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.module.scss, src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx
=> EPMDJ-2174: Added virtualization for the risk panel

src/pages/agents-page/table-view/name-column/name-column.module.scss, src/pages/agents-page/table-view/name-column/name-column.tsx, src/pages/agents-page/table-view/table-view.tsx
=> EPMDJ-2179: added margin for serive-group agents

src/components/menu/menu.tsx, src/components/toolbar/toolbar.module.scss, src/components/toolbar/toolbar.tsx, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes-modal.module.scss, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes-modal.tsx, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes.ts, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/index.ts, src/pages/service-group-full-page/service-group-dashboard/service-group-dashboard.tsx, src/routes/page-switcher.tsx
=> EPMDJ-2182: added bulk active scope finishing for service groups

src/pages/service-group-full-page/service-group-dashboard/service-group-dashboard.tsx
=> EPMDJ-2210: Corrected "Builds list" option name in menu SG dashboard

src/components/message-panel/message-panel.tsx, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes-modal.tsx, src/types/message.ts
=> EPMDJ-2182: added force redirect after finish all scopes

src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes-modal.module.scss, src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes-modal.tsx
=> EPMDJ-2215: Changed text and indents

src/forms/inputs/button/button-types.ts, src/forms/inputs/button/button.tsx, src/forms/inputs/button/cancel-button/cancel-button.tsx, src/forms/inputs/button/link-button/link-button.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.module.scss, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-2084: fix button sizes

src/pages/service-group-full-page/service-group-dashboard/finish-all-scopes-modal/finish-all-scopes.ts
=> EPMDJ-2254: added iternal service error message to finish all scopes

src/pages/settings-page/settings-page.tsx, src/pages/settings-page/toggle-standby.ts, src/types/message.ts, yarn.lock
=> EPMDJ-2254: added general error to toggle agent at settings page

.editorconfig, package.json, src/components/list/list.module.scss, src/components/menu/menu.module.scss, src/components/plugin-list-entry/plugin-list-entry.module.scss, src/components/table/table.module.scss, src/forms/inputs/dropdown-input/dropdown-input.module.scss, src/forms/inputs/dropdown/dropdown.module.scss, src/pages/agents-page/table-view/table/table.module.scss, src/pages/login-page/login-page.module.scss, src/pages/login-page/login-page.tsx, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/add-plugins-modal.module.scss, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.module.scss, src/pages/settings-page/settings-page.module.scss, src/pages/settings-page/settings-page.tsx
=> EPMDJ-2253: Changed color of selecred items from yellow to gray

src/components/table/table.module.scss, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agents-page/table-view/table/table.module.scss
=> EPMDJ-2253: fix hover backgroud color at non-white backgrounds

src/components/menu/menu.tsx, src/pages/service-group-full-page/service-group-dashboard/dashboard-cell/dashboard-cell.module.scss, src/pages/service-group-full-page/service-group-dashboard/dashboard-cell/dashboard-cell.tsx, src/pages/service-group-full-page/service-group-dashboard/dashboard-coverage-cell/dashboard-coverage-cell.tsx, src/pages/service-group-full-page/service-group-dashboard/dashboard-header-cell/dashboard-header-cell.tsx, src/pages/service-group-full-page/service-group-dashboard/dashboard-name-cell/dashboard-name-cell.tsx, src/pages/service-group-full-page/service-group-dashboard/service-group-dashboard.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.tsx, src/types/component-props-type.ts, src/utils/index.ts, src/utils/spaces-to-dashes.spec.ts, src/utils/spaces-to-dashes.ts
=> EPMDJ-2275: Added data-test attribute

src/components/list/list.tsx, src/components/list/list__row.tsx, src/pages/service-group-full-page/service-group-dashboard/service-group-dashboard.tsx, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.module.scss, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.tsx
=> EPMDJ-2279: Added space between the checkbox and the icon

src/pages/service-group-registration-page/service-group-registration-page.module.scss, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-2284: Added text "Choose plugins to install" and update styles

src/pages/service-group-full-page/service-group-dashboard/service-group-dashboard.tsx
=> EPMDJ-2339: fix test to run panel at service-group dashboard

src/pages/service-group-full-page/dashboard/dashboard.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-2219: added tooltip to test2code service group dashboard

src/pages/agent-full-page/coverage-plugin/test-details/no-tests-stub/no-tests-stub.tsx
=> EPMDJ-2378: Change "autotests" to "tests" text on empty tests tab

src/modules/tests-to-run-modal/admin-url.ts, src/modules/tests-to-run-modal/get-test-to-run-url.ts, src/modules/tests-to-run-modal/test-to-run-url.module.scss, src/modules/tests-to-run-modal/test-to-run-url.tsx, src/modules/tests-to-run-modal/tests-to-run-modal.module.scss, src/modules/tests-to-run-modal/tests-to-run-modal.tsx
=> EPMDJ-2355: Change the view of curl comand

src/pages/agent-full-page/coverage-plugin/covarage-plugin-modals.tsx
=> EPMDJ-2394: Fixed start "Manage Sessions" after the first login

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss
=> EPMDJ-1608: Add cursor:pointer for values in "Associated tests" pane

src/modules/tests-to-run-modal/get-test-to-run-url.ts
=> EPMDJ-2409: Correct working of the copy button on the "TestsToRun" pane

.github/workflows/bump-version.yml, Dockerfile, nginx/nginx.conf, nginx/upsteam.conf.template
=> EPMDJ-2068. Upstream setting has been set via including template and "envsubst" injection.

src/hooks/use-agent.ts, src/hooks/use-common-entity.ts, src/modules/manage-sessions-modal/manage-session.ts, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/api/delete-scope.ts, src/pages/agent-full-page/coverage-plugin/api/finish-scope.ts, src/pages/agent-full-page/coverage-plugin/api/rename-scope.ts, src/pages/agent-full-page/coverage-plugin/api/toggle-scope.ts, src/pages/agent-registration-page/install-plugins-step/install-plugins-step.tsx, src/pages/agent-registration-page/register-agent.ts, src/pages/agents-page/agents-page.tsx, src/pages/agents-page/agents-table/agents-table.tsx, src/pages/service-group-full-page/service-group-full-page.tsx, src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes.ts, src/pages/service-group-full-page/use-plugin-data.ts, src/pages/service-group-registration-page/register-service-group.ts, src/pages/service-group-registration-page/service-group-registration-page.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.tsx, src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/settings-page.tsx, src/pages/settings-page/toggle-agent.ts, src/pages/settings-page/unregister-agent-modal/unregister-agent-modal.tsx
=> EPMDJ-2312: support new backend API

src/pages/agent-full-page/plugin-header/plugin-header.module.scss, src/pages/agent-full-page/plugin-header/plugin-header.tsx
=> EPMDJ-2418: Add the gear button to the plugin-header

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss
=> EPMDJ-2417: Add space between Scope Info elements

src/common/style-guide/_colors.scss, src/forms/inputs/button/cancel-button/cancel-button.module.scss, src/pages/agent-full-page/coverage-plugin/code-coverage-card/coverages-by-type/coverages-by-type.module.scss, src/pages/agent-full-page/coverage-plugin/code-coverage-card/detailed-code-coverage-card/coverage-distribution/coverage-distribution.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
=> EPMDJ-2428: Update design in test2code and scope page

src/pages/agent-registration-page/register-agent.ts, src/pages/service-group-registration-page/register-service-group.ts
=> EPMDJ-2460: change register endpoint from post to patch

src/modules/breadcrumbs/breadcrumbs.tsx, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-2461: change build list and scopes list headers

src/modules/manage-sessions-modal/manage-session.ts, src/modules/manage-sessions-modal/manage-sessions-modal.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-2465: Fixed the launch "Manage Sessions" for service group

src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx
=> EPMDJ-2479: fix agent config settings API

src/pages/agent-full-page/build-list/build-list.tsx, src/utils/date-formatter.spec.ts, src/utils/date-formatter.ts, src/utils/index.ts
=> EPMDJ-2475: Return the "date added" column to the "all builds" table

src/pages/service-group-registration-page/service-group-registration-page.module.scss
=> EPMDJ-2490: Update styles SG registration for high-resolution screens

src/pages/agent-full-page/coverage-plugin/api/delete-scope.ts, src/pages/agent-full-page/coverage-plugin/code-coverage-card/code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/code-coverage-card/detailed-code-coverage-card/detailed-code-coverage-card.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-actions/active-scope-actions.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/scope-summary/scope-summary.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/store/reducer.ts, src/pages/agent-full-page/coverage-plugin/store/store-types.ts, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-section.tsx, src/types/active-scope.ts, src/types/build-coverage.ts, src/types/scope-summary.ts
=> EPMDJ-2504: refactor active scope API

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/scope-summary/scope-summary.tsx
=> EPMDJ-2504: refactor finish scope modal after API changes

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-2504: change coverage API

src/modules/tests-to-run-modal/get-test-to-run-url.ts, src/modules/tests-to-run-modal/test-to-run-url.tsx
=> EPMDJ-2507: change test to run url

src/common/connection/configure-axios.ts, src/common/connection/default-ws-connection.ts, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/pages/service-group-full-page/dashboard/dashboard.tsx, src/pages/service-group-full-page/service-group-full-page.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx, src/pages/service-group-full-page/use-plugin-data.ts, src/types/service-group-summary.ts
=> EPMDJ-2532: refactored service group dashboard after API changes

src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.tsx
=> EPMDJ-2553: remove redirect after finish all scopes

src/modules/breadcrumbs/breadcrumbs.module.scss, src/modules/breadcrumbs/breadcrumbs.tsx
=> EPMDJ-2283: Implement breadcrumbs functionality

package.json, src/modules/breadcrumbs/breadcrumbs.tsx, yarn.lock
=> EPMDJ-2563: update socket version to 0.1.5

package.json, src/hooks/use-agent.ts, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/pages/service-group-full-page/use-plugin-data.ts, yarn.lock
=> EPMDJ-2572: migration to new drill4j/socket version

src/pages/agent-full-page/plugin-header/plugin-header.module.scss
=> EPMDJ-2571: change offline agent status color to shade gray

src/pages/agent-registration-page/system-setting-form/system-settings-form.tsx, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.tsx
=> EPMDJ-2598: change packagesPrefixes placeholder

src/pages/agent-full-page/coverage-plugin/methods-sidebar/methods-sidebar.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/methods-section/methods-section.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-card/project-methods-card.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/types/methods.ts
=> EPMDJ-2709: method section API refactoring

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-2717: fix scope-info packages topic

src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-2740: change topic subscription queue

src/components/footer/footer.module.scss, src/components/footer/footer.tsx, src/components/toolbar/notifications-sidebar/notification/notification.module.scss, src/components/wizard/wizard.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-registration-page/general-settings-form/general-settings-form.tsx, src/pages/agent-registration-page/install-plugins-step/install-plugins-step.module.scss, src/pages/agent-registration-page/install-plugins-step/install-plugins-step.tsx, src/pages/service-group-registration-page/service-group-registration-page.module.scss, src/pages/service-group-registration-page/service-group-registration-page.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.module.scss, src/pages/settings-page/agent-settings/plugins-settings/add-plugins-modal/selectable-list/selectable-list.tsx, src/pages/settings-page/agent-settings/plugins-settings/plugins-settings.module.scss, src/pages/settings-page/agent-settings/plugins-settings/plugins-settings.tsx, src/types/agent.ts, src/types/drill-version.ts, src/types/plugin.ts
=> EPMDJ-2746: Add Drill artefact versions displaying

src/pages/agents-page/agents-table/name-column/name-column.tsx
=> EPMDJ-2766: Add number agents after the SG name

src/modules/system-setting-step/system-settings-step.module.scss, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-2782: Update styles & text in info panel & SG registration button

src/forms/form-validators.spec.ts, src/forms/form-validators.ts, src/modules/system-setting-step/system-settings-step.module.scss, src/modules/system-setting-step/system-settings-step.tsx, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/register-agent.ts, src/pages/service-group-registration-page/register-service-group.ts, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.module.scss, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.tsx, src/pages/settings-page/service-group-settings/system-setting-form/system-settings-form.tsx, src/routes/page-switcher.tsx, src/types/agent.ts, src/types/system-settings.ts
=> EPMDJ-2897: added target host to agent registation and system setting

src/pages/agent-full-page/build-list/build-list.tsx, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.tsx, src/pages/settings-page/service-group-settings/system-setting-form/system-settings-form.module.scss, src/pages/settings-page/service-group-settings/system-setting-form/system-settings-form.tsx, src/types/build-version.ts
=> EPMDJ-2898: update build list to new API

src/components/quality-gate-pane/quality-gate-pane.tsx, src/components/quality-gate-pane/quality-gate-settings/quality-gate-settings.tsx, src/components/quality-gate-pane/quality-gate-status/condition/condition.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx, src/utils/index.ts, src/utils/parse-coverage.spec.ts, src/utils/parse-coverage.ts
=> EPMDJ-2934: Fix button. Add percentFormatter for thresholdValue

src/pages/agent-full-page/new-build-modal/new-build-modal.tsx
=> EPMDJ-2945: fix typeerror at new build modal

src/common/connection/default-ws-connection.ts, src/common/connection/index.ts, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/pages/login-page/login-page.tsx, src/pages/service-group-full-page/use-plugin-data.ts
=> EPMDJ-3048: switch test2code plugin socket to new endpoint

src/pages/service-group-registration-page/register-service-group.ts
=> EPMDJ-3036: remove hardcoded petclinic project packages

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-status/index.ts, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-status/scope-status.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-status/scope-status.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-timer/scope-timer.tsx
=> EPMDJ-2890: Add recording/finished/ignored statuses.

src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-3114: Add redirect after finish scope to Test2Code

src/components/info-card/info-card.module.scss, src/components/info-card/info-card.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/build-coverage-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-3101: Support latest UX changes

src/pages/agent-full-page/coverage-plugin/overview/multi-progress-bar/multi-progress-bar.module.scss, src/pages/agent-full-page/coverage-plugin/overview/multi-progress-bar/multi-progress-bar.tsx
=> EPMDJ-3100: Correct display overlapped and uniqueСoverage progress bar

src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/multi-progress-bar/multi-progress-bar.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-coverage-info/scope-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-status/scope-status.tsx
=> EPMDJ-3341: Add new data-test attributes

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss
=> EPMDJ-3101: Add correct margin between ScopeName and Status

src/pages/service-group-registration-page/register-service-group.ts
=> EPMDJ-3344: Add headerMapping and targetHost in registration request

src/pages/service-group-full-page/dashboard/dashboard.tsx
=> EPMDJ-3323: Correct pluginLink for display Breadcrumbs

src/pages/agent-full-page/agent-full-page.tsx
=> EPMDJ-3347: Updated useEffect deps for correct appearances NewBuildModal

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
=> EPMDJ-2892: Update Test2code Header

src/modules/system-setting-step/system-settings-step.tsx, src/pages/settings-page/agent-settings/system-setting-form/system-settings-form.tsx, src/pages/settings-page/service-group-settings/system-setting-form/system-settings-form.tsx
=> EPMDJ-3425: update instruction message at system settings

package-lock.json, package.json, src/forms/fields/index.ts, src/hooks/index.ts, src/hooks/use-visible-elements-count.ts, src/modules/index.ts, src/modules/table-actions/index.ts, src/modules/table-actions/reducer.ts, src/modules/table-actions/table-actions-context.ts, src/modules/table-actions/table-actions-provider.tsx, src/modules/table-actions/table-actions-types.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/expandable-table/expandable-table.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/types/build-coverage.ts, src/types/scope-coverage.ts, yarn.lock
=> EPMDJ-3105: Search filtering. Sorting

src/modules/index.ts, src/modules/table-actions/index.ts, src/modules/table-actions/reducer.ts, src/modules/table-actions/table-actions-context.ts, src/modules/table-actions/table-actions-types.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/pages/agent-full-page/coverage-plugin/use-build-version.ts
=> EPMDJ-3627: Add new action "toogleOrder" to switch sorting correctly

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx
=> EPMDJ-3645: Add ZeroValue instead of n/a

package-lock.json, package.json, yarn.lock
=> EPMDJ-3571: upgrade ui-kit version

src/pages/agent-full-page/coverage-plugin/api/finish-scope.ts
=> EPMDJ-3616: Add error message if there is no connection

src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx
=> EPMDJ-3787: Update the calculation of the unique number of methods

src/modules/manage-sessions-pane/manage-sessions-pane.tsx, src/modules/manage-sessions-pane/use-active-sessions.ts
=> EPMDJ-4327: Add clearing of the previous sessionID. Fix useEffect deps

src/modules/manage-sessions-pane/manage-active-sessions/empty-active-sessions-stub/empty-active-sessions-stub.module.scss, src/modules/manage-sessions-pane/manage-active-sessions/empty-active-sessions-stub/empty-active-sessions-stub.tsx, src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.module.scss
=> EPMDJ-4336: Correct the centering of the stub

src/components/toolbar/notifications-sidebar/api/delete-all-notifications.ts, src/components/toolbar/notifications-sidebar/api/index.ts, src/components/toolbar/notifications-sidebar/api/read-all-notifications.ts, src/components/toolbar/notifications-sidebar/notifications-sidebar.module.scss, src/components/toolbar/notifications-sidebar/notifications-sidebar.tsx
=> EPMDJ-4369: Notifications - Bulk Operations integration

src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.module.scss
=> EPMDJ-4328: not visible disabled test session

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/use-build-version.ts, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/is-active-build.ts, src/pages/service-group-full-page/use-plugin-data.ts
=> EPMDJ-3848: Remove ScopeActions for non-latest builds

src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/use-previous-build-coverage.ts, src/pages/agent-full-page/dashboard/dashboard.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/types/build-coverage.ts, src/types/parent-build.ts, src/utils/percent-formatter.spec.ts, src/utils/percent-formatter.ts
=> EPMDJ-3218: Correct the calculation of the unique coverage

src/hooks/use-general-alert-message.ts, src/notification-manager/notification-manager.tsx
=> EPMDJ-4410: Сhange the notification bar life time

src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-4411: Change complete button to finish button

src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-4405: Update UI elements for scope action: delete

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPDDJ-4407: update UI scope action: include/ignore

src/pages/agent-full-page/coverage-plugin/api/delete-scope.ts, src/pages/agent-full-page/coverage-plugin/api/finish-scope.ts
=> EPMDJ-4784: Rename error message when deleting scope

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-4755: No redirect the user to Test2Code overview page after deleting an empty active scope

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-4407: Update UI scope actions: include/ignore

src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
=> EPMDJ-3753: Update Covered Methods Modal

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/scope-summary/scope-summary.tsx
=> EPMDJ-4809: Add data test attributes to UI elements

src/pages/service-group-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx, src/types/arrow-type.ts, src/types/service-group-summary.ts
=> EPMDJ-4871: Support ArrowType.UNCHANGED

src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss, src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-3644: add a stub with empty scopes

src/pages/agent-full-page/new-build-modal/build-updates/build-updates.module.scss, src/pages/agent-full-page/new-build-modal/header/header.module.scss, src/pages/agent-full-page/new-build-modal/header/header.tsx, src/pages/agent-full-page/new-build-modal/new-build-modal.module.scss, src/pages/agent-full-page/new-build-modal/new-build-modal.tsx, src/pages/agent-full-page/new-build-modal/recommended-actions/recommended-actions.module.scss
=> EPMDJ-4853: Add button "Go to New Build" for NewBuildModal. Update styles

src/pages/agents-page/agents-page.tsx
=> Correct the agents count display

src/pages/agents-page/agents-page.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.tsx, src/pages/agents-page/agents-table/agents-table.tsx, src/pages/agents-page/agents-table/name-column/name-column.tsx
=> EPMDJ-4959: Correct offline agents filter

src/pages/service-group-full-page/dashboard/sections/coverage-section/coverage-section.tsx
=> EPMDJ-4871: Add condition for service group arrow

src/pages/agent-full-page/coverage-plugin/scope/active-sessions-panel/active-sessions-panel.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-4790: changed warning message when delete scope with active session

src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/general-settings-form/general-settings-form.tsx
=> EPMDJ-5007: Add validation and placeholder for "Agent ID" field

package-lock.json, package.json, src/components/info-card/info-card.module.scss, yarn.lock
=> EPMDJ-4842: Update progress bar animation

src/components/cells/coverage-cell/coverage-cell.module.scss, src/components/cells/index.ts, src/components/cells/test-status-cell/index.ts, src/components/cells/test-status-cell/test-status-cell.module.scss, src/components/cells/test-status-cell/test-status-cell.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-4840: Update build/scope test table

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-4411: Correct redirects at finish scope

src/pages/agent-registration-page/agent-registration-page-api/preregister-offline-agent.ts
=> EPMDJ-5052: change error message at agent preregistration

src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
=> EPMDJ-4990: Remove test to run links from build tests card

src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx
=> EPMDJ-4955: move unique coverage text right in first build

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/new-build-modal/new-build-modal.tsx
=> EPMDJ-4936: Redirect from ScopeDetails to T2C if coverage = 0 & new build appeared

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/types/active-scope.ts
=> EPMDJ-4755: added redirect if scope is empty

src/forms/fields/error-message/error-message.module.scss, src/forms/fields/field.tsx, src/forms/form-validators.spec.ts, src/forms/form-validators.ts, src/forms/index.ts, src/modules/manage-sessions-pane/manage-sessions-pane-api/start-agent-session.ts, src/modules/manage-sessions-pane/manage-sessions-pane-api/start-service-group-sessions.ts, src/modules/manage-sessions-pane/manage-sessions-pane.tsx
=> EPMDJ-4917: Add onSubmit validation

package-lock.json, package.json, public/index.html, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/multi-progress-bar/multi-progress-bar.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/dashboard/sections/risks-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx, yarn.lock
=> EPMDJ-3047: Integrate new ui-kit tooltip

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/index.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/tests-list.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/tests-list.tsx
=> EPMDJ-4944: Update associated tests modal

src/hooks/use-build-version.ts, src/modules/table-actions/reducer.ts, src/modules/table-actions/table-actions-context.ts, src/modules/table-actions/table-actions-types.ts, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/default-header-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table-types.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/types/search.ts, src/types/sort.ts
=> EPMDJ-5058: integration with new sort/filter realization

src/modules/manage-sessions-pane/manage-sessions-pane.tsx
=> EPMDJ-5115: improve validation on start new session

package-lock.json, package.json, src/forms/form-validators.ts, src/modules/manage-sessions-pane/active-sessions-list/active-sessions-list.tsx, src/modules/manage-sessions-pane/active-sessions-list/service-group-sessions/service-group-sessions.tsx, src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.module.scss, src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx, src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss, src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx, src/modules/manage-sessions-pane/manage-sessions-pane-api/start-agent-session.ts, src/modules/manage-sessions-pane/manage-sessions-pane-api/start-service-group-sessions.ts, src/modules/manage-sessions-pane/manage-sessions-pane-api/start-session-payload-types.ts, src/modules/manage-sessions-pane/manage-sessions-pane.tsx, src/types/active-session.ts, yarn.lock
=> EPMDJ-4918: Implement the ability to configure the session start as global and real-time

src/pages/agent-full-page/coverage-plugin/api/rename-scope.ts
=> EPMDJ-5140: Add stub error message for rename scope

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-5154: improve redirect logic from all scopes page to scope

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.module.scss, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-5141: Improve finish scope modal's header when scope name so long

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-5143: Change rename scope validation message

src/modules/index.ts, src/modules/table-actions/index.ts, src/modules/table-actions/reducer.ts, src/modules/table-actions/table-actions-context.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/default-header-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table-types.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/types/sort.ts
=> EPMDJ-5210: Update sorting/filtering topic state

src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.module.scss, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx
=> EPMDJ-5203: improve delete scope modal

src/hooks/use-general-alert-message.ts, src/notification-manager/notification-manager.tsx
=> EPMDJ-5207: change the time when notification disappear

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-5208: change the validation message

src/hooks/use-build-version.ts, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/types/filter-list.ts, src/types/output-type.ts
=> EPMDJ-5158: Support new subscription field: output type

src/modules/quality-gate-pane/quality-gate-pane.tsx, src/types/quality-gate-type.ts
=> EPMDJ-5209: Stabilization QG settings page

package-lock.json, src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.module.scss, src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx, yarn.lock
=> EPMDJ-5212: Improve display of icons in the session manager

src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.module.scss, src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
=> EPMDJ-5224: Add system tooltip for session's name. Improve display of icons

src/forms/form-validators.spec.ts, src/forms/form-validators.ts, src/hooks/use-general-alert-message.ts, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/quality-gate-pane/quality-gate-settings/quality-gate-settings.tsx
=> EPMDJ-5223: Improve validation

src/pages/agent-full-page/new-build-modal/build-updates/build-updates.tsx, src/pages/agent-full-page/new-build-modal/header/header.module.scss, src/pages/agent-full-page/new-build-modal/header/header.tsx, src/pages/agent-full-page/new-build-modal/new-build-modal.tsx, src/types/build-info.ts, src/types/build-version.ts, src/types/notificaiton.ts
=> EPMDJ-5262: Support new api for NewBuildPopup and "All builds" table

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.module.scss, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-5230: Update rename scope modal

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-status/scope-status.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-5231: update scope name block on scope details and all scope page

src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-5289: update redirect logic to agent from agent list

src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
=> EPMDJ-5284: Remove "Get Suggested Tests" button from non-latest builds

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/new-build-modal/new-build-modal.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-5289: remove 'Go to new build' button from latest build in new build modal

package-lock.json, package.json, src/hooks/use-build-version.ts, src/pages/agent-full-page/coverage-plugin/api/index.ts, src/pages/agent-full-page/coverage-plugin/api/toggle-baseline.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/index.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx, src/types/baseline.ts, yarn.lock
=> EPMDJ-5260: Add the ability to toggle baseline

src/components/list/list.module.scss, src/pages/service-group-full-page/service-group-header/service-group-header.module.scss, src/pages/service-group-full-page/service-group-header/service-group-header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.module.scss
=> EPMDJ-5233: Update service group test2code page overview

src/components/tabs/tabs.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-coverage-info/scope-coverage-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
=> EPMDJ-5234: Update active scope block

src/pages/agent-full-page/plugin-header/plugin-header.tsx
=> EPMDJ-5334: Add condition for unicorn in the non-latest build

src/components/cells/duration-cell/duration-cell.tsx, src/components/cells/duration-cell/getDuration.spec.ts, src/components/cells/duration-cell/getDuration.ts, src/utils/capitalize.spec.ts, src/utils/convert-to-percentage.spec.ts, src/utils/convert-to-percentage.ts, src/utils/format-ms-to-date.spec.ts, src/utils/format-ms-to-date.ts, src/utils/kebab-to-pascal-case.spec.ts, src/utils/percent-formatter.spec.ts
=> EPMDJ-5389: added tests to the utility functions

src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/dashboard/sections/risks-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-section.tsx, src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx, src/types/build-summary.ts, src/types/test-count.ts, src/utils/index.ts
=> EPMDJ-5316: support topic "/build/summary" for dashboard page

src/hooks/index.ts, src/hooks/use-active-scope.ts, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-5478: Remove /active-scope subscription on non-latest builds

src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.tsx
=> EPMDJ-5496: added optinal label to description form on settings page

src/hooks/use-general-alert-message.ts, src/modules/quality-gate-pane/api/update-quality-gate-settings.ts, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/quality-gate-pane/quality-gate-status/quality-gate-status.tsx
=> EPMDJ-5479: Correct the state update logic.

src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-coverage-cell/test-to-code-coverage-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-5477: updated tests to run blocks on single agent and SG t2c page

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx, src/types/risk-type.ts, src/types/risks.ts
=> EPMDJ-5316: Improve risks modal

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-5376: Improve warning message on finish scope

src/modules/system-setting-step/system-settings-step.tsx, src/modules/system-settings-form/system-settings-form.tsx, src/utils/format-packages.ts, src/utils/index.ts, src/utils/parse-packages.spec.ts, src/utils/parse-packages.ts, src/utils/parse-packges.spec.ts, src/utils/parse-packges.ts
=> EPMDJ-5539: Improve error message and project packages field validation in system settings

src/pages/agent-full-page/agent-full-page.tsx, src/pages/agent-full-page/sidebar/sidebar.module.scss, src/pages/agent-full-page/sidebar/sidebar.tsx, src/pages/service-group-full-page/service-group-full-page.tsx
=> EPMDJ-5596: Add tooltips for application sidebar

package-lock.json, package.json, src/common/constants/index.ts, src/common/constants/legend-colors.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/action-section/action-section.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-coverage-info/build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-coverage-info/scope-coverage-info.tsx, yarn.lock
Issue: EPMDJ-5543, EPMDJ-5540, EPMDJ-5578
=> EPMDJ-5543: update action-section component and legend

src/pages/agent-full-page/coverage-plugin/initial-data-controller.ts
=> EPMDJ-5334: Improve active unicorn for new build

src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-5613: Change error message in Project Packages field

src/pages/service-group-full-page/dashboard/dashboard.tsx, src/pages/service-group-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/service-group-full-page/dashboard/sections/coverage-section/methods-tooltip/methods-tooltip.tsx, src/types/service-group-summary.ts
=> EPMDJ-5614: Improve calculating percantage of covered methods on SG page

src/components/dashboard-section/dashboard-section.tsx
=> EPMDJ-5623: Add data-test attributes to dashboard

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/plugin-header/plugin-header.module.scss, src/pages/agent-full-page/plugin-header/plugin-header.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.tsx
=> EPMDJ-5628: Disable settings if agent is offline or unregister

src/layouts/login-layout/login-layout.module.scss, src/pages/login-page/login-page.module.scss, src/pages/login-page/login-page.tsx
=> EPMDJ-5611: Update login page

package-lock.json, package.json, src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/no-data-stub/index.ts, src/modules/tests-to-run/tests-to-run-list/no-data-stub/no-data-stub.module.scss, src/modules/tests-to-run/tests-to-run-list/no-data-stub/no-data-stub.tsx, src/modules/tests-to-run/tests-to-run-list/no-tests-to-run-stub/index.ts, src/modules/tests-to-run/tests-to-run-list/no-tests-to-run-stub/no-tests-to-run-stub.module.scss, src/modules/tests-to-run/tests-to-run-list/no-tests-to-run-stub/no-tests-to-run-stub.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/types/build-summary.ts, yarn.lock
=> EPMDJ-5593: Added t2r stubs

src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/index.ts, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/saved-time-section.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/saved-time-section.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/types/test-summary.ts
=> EPMDJ-5502: update header on tests to run page

src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
=> EPMDJ-5767: Update estimated time saved tooltip

src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/active-build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/multi-progress-bar/multi-progress-bar.tsx
=> EPMDJ-5629: Updated legend and coverage bar hints on Test2Code overview page

src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx
=> EPMDJ-5673: Update plugin modal on setting page

src/components/footer/footer.tsx
=> EPMDJ-5720: Update document link in footer

src/pages/agents-page/agents-table/agents-table.tsx
=> EPMDJ-5667: Update environment cell in agents page

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agent-full-page/coverage-plugin/tests/tests.tsx, src/types/test-stats.ts
=> EPMDJ-5622: Support new API for new Build/Scope Test Page

package-lock.json, package.json, src/hooks/index.ts, src/hooks/use-baseline-version.ts, src/pages/agent-full-page/build-list/build-list.module.scss, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.module.scss, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, yarn.lock
=> EPMDJ-5504: Update the display of baseline information

src/pages/agent-full-page/coverage-plugin/active-build-tests-info/active-build-tests-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-project-methods/scope-project-methods.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-project-methods/scope-project-methods.tsx
=> EPMDJ-5785: Updat overview build and scope page

package-lock.json, package.json, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/build-list/build-list.module.scss, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/default-header-cell.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table-row.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agents-page/agents-table/agents-table.tsx, yarn.lock
=> EPMDJ-5392: Integrate new Ui-kit tables

src/components/cards/build-methods-card.tsx, src/components/cards/build-tests-card.tsx, src/components/cells/clickable-cell/clickable-cell.tsx, src/components/cells/compound-cell/compound-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-cell/coverage-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/name-cell/name-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/default-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/expandable-table/row-expander/row-expander.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/expanded-row-content.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table-types.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__row.tsx
=> EPMDJ-5800: Added data-test attributes on overview page

package-lock.json, package.json, src/components/cells/coverage-cell/coverage-cell.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/build-list/build-list.module.scss, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-timer/scope-timer.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.module.scss, src/pages/agents-page/agents-table/actions-column/actions-column.tsx, src/pages/agents-page/agents-table/agents-table.tsx, yarn.lock
=> EPMDJ-5796: Updare table cells styles

src/utils/percent-formatter.spec.ts, src/utils/percent-formatter.ts
=> EPMDJ-4399: Add round value if coverage less than 0.1

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
=> EPMDJ-5799: Update baseline flag colors

package-lock.json, package.json, src/notification-manager/notification-manager.tsx, yarn.lock
=> EPMDJ-5797: Add error SystemAlert if the connection was closed

.github/workflows/check.yml, package-lock.json, package.json, src/components/cells/clickable-cell/clickable-cell.module.scss, src/components/cells/duration-cell/duration-cell.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/name-cell/name-cell.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.module.scss, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, yarn.lock
=> EPMDJ-5796: Update tables font size

src/modules/breadcrumbs/breadcrumbs.module.scss, src/modules/breadcrumbs/breadcrumbs.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/pages/agent-full-page/build-list/build-list.module.scss, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.module.scss, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx
=> EPMDJ-5841: Add text overflow for build names

package-lock.json, package.json, src/app.scss, src/app.tsx, yarn.lock
=> EPMDJ-5843: Integrate bootstrap

src/utils/get-duration.ts
=> EPMDJ-5858: Correct formatting of time values

src/components/cards/build-methods-card.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__row.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/build-project-methods.tsx, src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx
=> EPMDJ-5886: Add tooltip on risks pane

nginx/nginx.conf
=> EPMDJ-5907: Increase waiting time in nginx

src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/utils/get-duration.spec.ts, src/utils/get-duration.ts
=> EPMDJ-5895: Add tooltip on test to run bar and get duration function

nginx/nginx.conf
=> EPMDJ-5907: Add send_timeout in nginx.conf

src/modules/tests-to-run/tests-to-run-list/no-data-stub/no-data-stub.tsx
=> EPMDJ-5895: Update test to run stub message

src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx
=> EPMDJ-5855: Update search packages field placeholder

src/pages/agent-full-page/new-build-modal/header/header.module.scss, src/pages/agent-full-page/new-build-modal/header/header.tsx
=> EPMDJ-5909: Add overflow build name on new build modal

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
=> EPMDJ-5927: Update baseline tooltip

src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
=> EPMDJ-5925: Update tests to run header

src/modules/breadcrumbs/breadcrumbs.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.module.scss
=> EPMDJ-5841: Update build name overflow rules

src/app.scss, src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/saved-time-section.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/utils/percent-formatter.spec.ts, src/utils/percent-formatter.ts
=> EPMDJ-5906: Fix bar size if duration > totalDuration. Add new tooltips

src/components/wizard/wizard.tsx, src/modules/install-plugins-step/install-plugins-step.tsx, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-5943: Fix redirects and resetting the plugin selection after submiting

nginx/nginx.conf, package-lock.json, package.json, src/common/connection/default-ws-connection.ts, src/common/connection/drill-socket.ts, src/components/toolbar/toolbar.tsx, src/hooks/use-ws-connection.ts, src/notification-manager/notification-manager.tsx, src/pages/login-page/login-page.tsx, yarn.lock
=> EPMDJ-5863: Update rxjs subscription

src/modules/sessions-management-pane/use-active-sessions.ts, src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx, src/pages/agent-full-page/coverage-plugin/initial-data-controller.ts, src/pages/service-group-full-page/dashboard/dashboard.tsx, src/pages/service-group-full-page/service-group-full-page.tsx
=> EPMDJ-5787: Support new API for active scope

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
=> EPMDJ-5841: Correct coverage plugin header

src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.module.scss, src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
=> EPMDJ-5977: Update tooltips in t2r header and time-saved graph

package-lock.json, package.json, src/hooks/use-general-alert-message.ts, src/pages/agent-full-page/coverage-plugin/coverage-details/table/expanded-row-content.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/second-level-expand-content.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, yarn.lock
=> EPMDJ-5958: Fix console warnings

package-lock.json, package.json, src/components/wizard/wizard.module.scss, src/components/wizard/wizard.tsx, src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/sessions-management-pane/actions-panel/actions-panel.tsx, src/modules/sessions-management-pane/sessions-management-pane.tsx, src/modules/system-settings-form/system-settings-form.module.scss, src/modules/system-settings-form/system-settings-form.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.module.scss, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.module.scss, src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/unregister-agent-modal/unregister-agent-modal.module.scss, src/pages/settings-page/unregister-agent-modal/unregister-agent-modal.tsx, yarn.lock
=> EPMDJ-5980: Add loading indicators

src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.module.scss, src/modules/tests-to-run/tests-to-run-url.tsx
=> EPMDJ-6000: Update tests to run modal

src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-6004: Update tests details table label

src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx
=> EPMDJ-6025: Update delete scope modal message

src/modules/sessions-management-pane/sessions-management-pane-api/abort-all-sessions.ts, src/modules/sessions-management-pane/sessions-management-pane-api/abort-session.ts, src/modules/sessions-management-pane/sessions-management-pane-api/finish-all-sessions.ts, src/modules/sessions-management-pane/sessions-management-pane-api/finish-session.ts, src/modules/sessions-management-pane/sessions-management-pane.tsx
=> EPMDJ-6026: Update manage session pane error message

src/app.scss, src/components/toolbar/notifications-sidebar/notification/notification.module.scss, src/components/toolbar/notifications-sidebar/notification/notification.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/new-build-modal/header/header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx
=> EPMDJ-6008: Update notification panel

src/app.scss, src/modules/quality-gate-pane/quality-gate-status/quality-gate-configuration-url.module.scss, src/modules/quality-gate-pane/quality-gate-status/quality-gate-configuration-url.tsx, src/modules/quality-gate-pane/quality-gate-status/quality-gate-status.module.scss, src/modules/quality-gate-pane/quality-gate-status/quality-gate-status.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/get-suggested-tests-modal/get-suggested-tests-modal.module.scss, src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/get-suggested-tests-modal/get-suggested-tests-modal.tsx, src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.module.scss, src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx, src/modules/tests-to-run/tests-to-run-url.module.scss, src/modules/tests-to-run/tests-to-run-url.tsx
=> EPMDJ-6001: Update "Copy to clipboard" functionality

src/notification-manager/notification-manager.tsx
=> EPMDJ-5887: Add useMemo to notification context 

src/hooks/use-general-alert-message.ts, src/modules/sessions-management-pane/management-new-session/management-new-session.tsx, src/modules/sessions-management-pane/sessions-management-pane.tsx
=> EPMDJ-6035: Disable the start of the second global session. Add tooltip

src/components/toolbar/notifications-sidebar/notification/notification.module.scss, src/components/toolbar/notifications-sidebar/notification/notification.tsx
=> EPMDJ-6008: Update display build version on notification panel

src/pages/agent-full-page/dashboard/plugin-card/plugin-card.module.scss, src/pages/agent-full-page/dashboard/plugin-card/plugin-card.tsx
=> EPMDJ-6063: Update plugin link markup on dashboard page

package-lock.json, package.json, src/components/wizard/wizard.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/sessions-management-pane/actions-panel/actions-panel.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agents-page/agents-page.tsx, src/pages/login-page/login-page.module.scss, yarn.lock
=> EPMDJ-6058: Update buttons

src/app.scss, src/pages/login-page/login-page.module.scss, src/pages/login-page/login-page.tsx
=> EPMDJ-6073: Update login form error message

src/notification-manager/notification-manager.tsx, src/pages/login-page/login-page.tsx
=> EPMDJ-6080: Removed SystemAlert on the login page

.babelrc, babel-plugin-macros.config.js, package-lock.json, package.json, tsconfig.json, twin.d.ts, yarn.lock
=> EPMDJ-6083: Add tailwind macro

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/active-build-coverage-info/active-build-coverage-info.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/active-build-coverage-info/multi-progress-bar/multi-progress-bar.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-coverage-info/scope-coverage-info.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx
=> EPMDJ-6036: Fix bold text in firefox

src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/modules/sessions-management-pane/sessions-management-pane-api/abort-all-sessions.ts, src/modules/sessions-management-pane/sessions-management-pane-api/finish-all-sessions.ts, src/modules/sessions-management-pane/sessions-management-pane-api/start-service-group-sessions.ts, src/modules/system-settings-form/system-settings-form.tsx, src/modules/tests-to-run/get-tests-to-run-url.ts, src/modules/tests-to-run/tests-to-run-url.tsx, src/pages/agents-page/agents-page.tsx, src/pages/service-group-full-page/service-group-full-page.tsx, src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes.ts, src/pages/service-group-registration-page/service-group-registration-page.tsx, src/pages/settings-page/service-group-settings/general-settings-form/general-settings-form.tsx, src/types/agent.ts
=> EPMDJ-6027: Update service group topics

src/pages/login-page/login-page.tsx
=> EPMDJ-6120: Add reload after redirect on login page

src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.module.scss, src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx
=> EPMDJ-5961: Add dynamically change the slider of a custom scrollbar

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-project-methods/scope-project-methods.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-project-tests/scope-project-tests.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-5788: Support new API for scopes

src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx
=> EPMDJ-6178: Add validation rule for register and configure JS agent

src/index.css, src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/sessions-management-pane/actions-panel/actions-panel.tsx, src/modules/sessions-management-pane/active-sessions-list/session-info/single-operation-warning/single-operation-warning.tsx, src/modules/sessions-management-pane/bulk-operation-warning/bulk-operation-warning.tsx, src/modules/sessions-management-pane/operation-action-warning/operation-action-warning.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx, tailwind.config.js
=> EPMDJ-6139: Support loading state in buttons

src/modules/system-settings-form/system-settings-form.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx
=> EPMDJ-6265: Lock packages field after save changes in system settings

src/pages/settings-page/agent-settings/java-general-settings-form/java-general-settings-form.tsx, src/pages/settings-page/agent-settings/js-general-settings-form/js-general-settings-form.tsx, src/pages/settings-page/service-group-settings/service-group-general-settings-form/service-group-general-settings-form.tsx
=> EPMDJ-6263: Update fields placeholder on settings

src/components/wizard/wizard.tsx
=> EPMDJ-6266: Change error message type on wizard

src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/sessions-management-pane/sessions-management-pane.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx
=> EPMDJ-6173: Add forms submit handle on press enter

src/pages/settings-page/agent-settings/java-general-settings-form/java-general-settings-form.tsx, src/pages/settings-page/agent-settings/js-general-settings-form/js-general-settings-form.tsx
=> EPMDJ-6254: Up enviroment field above on Java settings

src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/settings-page/agent-settings/js-system-settings-form/js-system-settings-form.tsx
=> EPMDJ-6261: Update hint in the system js agent settings

package-lock.json, package.json, src/components/toolbar/toolbar.module.scss, src/components/toolbar/toolbar.tsx, src/index.css, src/modules/breadcrumbs/breadcrumbs.module.scss, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/dashboard/plugin-card/plugin-card.tsx, src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx, src/pages/agent-full-page/plugin-header/plugin-header.module.scss, src/pages/agent-full-page/plugin-header/plugin-header.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.tsx, src/pages/agents-page/agents-table/name-column/name-column.tsx, src/tailwind.css, yarn.lock
=> EPMDJ-6276: Update links style

src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx
=> EPMDJ-6321: Add margin for bar chart range input

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-6272: Add pristine to rename scope modal form

src/components/wizard/wizard.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.tsx
=> EPMDJ-6278: Hide settings button when SG has offline or unregister agent

src/components/wizard/wizard.tsx, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/service-group-registration-page/service-group-general-registration-form/index.ts, src/pages/service-group-registration-page/service-group-general-registration-form/service-group-general-registration-form.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx
=> EPMDJ-6138: Add general tab to service group registration

src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-6351: Add infinite scroll for test-details

src/pages/agent-full-page/coverage-plugin/initial-data-controller.ts
=> EPMDJ-6340: Stoped recording session for the offline agent

src/pages/service-group-registration-page/service-group-general-registration-form/service-group-general-registration-form.tsx, src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-6138: Correct messages in register service group general tab

src/modules/sessions-management-pane/actions-panel/actions-panel.tsx, src/modules/sessions-management-pane/management-active-sessions/management-active-sessions.tsx
=> EPMDJ-6322: Add preventDefault to start new session button

src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/build-coverage-info/build-coverage-info.tsx
=> EPMDJ-6310: Add condition to displaying comparison text

src/modules/breadcrumbs/breadcrumbs.module.scss, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.module.scss, src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/build-coverage-info/build-coverage-info.tsx, src/pages/service-group-full-page/dashboard/plugin-card/plugin-card.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.module.scss, src/pages/service-group-full-page/service-group-header/service-group-header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.module.scss, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx
=> EPMDJ-6276: Update link styles

src/modules/breadcrumbs/breadcrumbs.tsx, src/modules/no-plugins-stub/no-plugins-stub.tsx, src/modules/sessions-management-pane/management-new-session/management-new-session.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.tsx
=> EPMDJ-6357: Update settings links

src/modules/breadcrumbs/breadcrumbs.tsx, src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx
=> EPMDJ-6138: Remove auto install plugin in registration

src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx
=> EPMDJ-6276: Update links styles in active scope info component

src/components/wizard/wizard.tsx, src/modules/system-settings-form/system-settings-form.tsx, src/pages/agents-page/agents-table/name-column/name-column.module.scss, src/pages/agents-page/agents-table/name-column/name-column.tsx
=> EPMDJ-6361: Update icons margin in agents table

src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx
=> EPMDJ-6353: Add padding in coverage details package name cell

src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/modules/system-settings-form/system-settings-form.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/agent-settings/js-system-settings-form/js-system-settings-form.tsx, src/pages/settings-page/service-group-settings/service-group-general-settings-form/service-group-general-settings-form.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx, src/pages/settings-page/un-save-changes-modal/un-save-changes-modal.tsx
=> EPMDJ-6304: Align button in settings

src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/tests-list.tsx
=> EPMDJ-6359: Fix methods filter

src/index.css, src/pages/agents-page/agents-table/name-column/name-column.module.scss, src/pages/agents-page/agents-table/name-column/name-column.tsx, src/tailwind.css, tailwind.config.js
=> EPMDJ-6358: Add title to agent in agents table

src/common/connection/drill-socket.ts
=> EPMDJ-6341: Clear token when socket catch status 401

src/pages/agent-full-page/coverage-plugin/build-tests/build-tests.tsx, src/pages/agent-full-page/coverage-plugin/build-tests/index.ts, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope-tests/index.ts, src/pages/agent-full-page/coverage-plugin/scope-tests/scope-tests.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-6367: Add search in tests table

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-6367: Add margin in scope tests table

src/forms/form-validators.ts, src/pages/agent-registration-page/agent-registration-page.tsx
=> EPMDJ-6308: Add possibility agent registration with id more than 32 symbols

src/modules/sessions-management-pane/sessions-management-pane-api/abort-all-sessions.ts
=> EPMDJ-6473: Update abort all sessions success message

package-lock.json, package.json, src/index.css, src/modules/index.ts, src/modules/no-results-found-stub/index.ts, src/modules/no-results-found-stub/no-results-found-stub.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/expanded-row-content.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/second-level-expand-content.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__row.tsx, src/pages/agent-full-page/coverage-plugin/test-details/no-tests-stub/no-tests-stub.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, yarn.lock
=> EPMDJ-6367: Add no results stub for tests table

src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-6367: Update incorrect icons in tables stubs

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
=> EPMDJ-6514: Remove tooltip if hover on empty place

src/index.css, src/modules/system-setting-step/system-settings-step.tsx, src/modules/system-settings-form/system-settings-form.tsx, src/utils/dots-and-slashes-to-slash.spec.ts, src/utils/dots-and-slashes-to-slash.ts, src/utils/index.ts
=> EPMDJ-6481: add parse dots to slashes in the field with packages

src/hooks/index.ts, src/hooks/use-intersection.ts, src/modules/tests-to-run/tests-to-run-list/bar-chart/bar-chart.tsx, src/modules/tests-to-run/tests-to-run-list/bar-chart/chart.tsx
=> EPMDJ-5860: Hide tooltip when part of bar chart is not visible

src/index.css, src/pages/agent-registration-page/agent-registration-page.tsx, src/pages/agent-registration-page/java-general-registration-form/java-general-registration-form.tsx, src/pages/agent-registration-page/js-general-registration-form/js-general-registration-form.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx
=> EPMDJ-6539: Make target host optional for js agent in SG

src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes.ts
=> EPMDJ-6574: Update error message in finish all scopes

src/components/toolbar/toolbar.tsx
=> EPMDJ-6621: Add rounding for notification count block

src/components/cards/build-tests-card.tsx, src/components/cells/compound-cell/compound-cell.tsx, src/components/dashboard-section/dashboard-section.tsx, src/modules/install-plugins-step/install-plugins-step.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-cell/coverage-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/table/table__header.tsx, src/pages/agent-full-page/coverage-plugin/overview/build-project-methods/build-project-methods.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.tsx, src/pages/settings-page/agent-settings/agent-settings.tsx, src/pages/settings-page/service-group-settings/service-group-settings.tsx
=> EPMDJ-6675: Implement new design changes

src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx
=> EPMDJ-6716: Fix virtual scroll height

src/components/wizard/wizard.tsx, src/modules/install-plugins-step/install-plugins-step.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-cell/coverage-cell.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-header-cell/test-to-code-header-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx
=> EPMDJ-6675: Add new design changes

src/components/wizard/wizard.tsx
=> EPMDJ-6723: Prevent reset the state when changing the form

package-lock.json, package.json
=> EPMDJ-6721: Update ui-kit. Add a sticky header for all tables

src/index.css, src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx, src/pages/agent-full-page/coverage-plugin/build-tests/build-tests.tsx, src/pages/agent-full-page/coverage-plugin/scope-tests/scope-tests.tsx, src/types/methods-covered-by-test-summary.ts
=> EPMDJ-6720: Add new topics to covered methods panel

src/index.css, src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
=> EPMDJ-6720: Display name instead id in hint in methods covered panel

src/common/connection/drill-socket.ts, src/notification-manager/notification-manager.tsx
=> EPMDJ-6051: Add auto reconnecting for socket

src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
=> EPMDJ-6779: Change covered methods topic on t2r page

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-6175: Add id for associatedTestsTopic

src/modules/sessions-management-pane/sessions-management-pane.tsx, src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx
=> EPMDJ-6841: Fix display of success messages & display of tests list

src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx
=> EPMDJ-6837: Add gap between header & curl

src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
=> EPMDJ-6729: Add infinite scroll for tests to run table

src/pages/agents-page/agents-table/agents-table.tsx
=> EPMDJ-6726: Fix n/a dispaly logic

src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/tests-list.tsx
=> EPMDJ-6847: Update styles in "Associated tests" pane

src/components/search-panel/search-panel.tsx
=> EPMDJ-6762: Update input width

src/pages/service-group-full-page/test-to-code-plugin/test-to-code-name-cell/test-to-code-name-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-6714: Improve SG dashboard links

src/components/search-panel/search-panel.tsx, src/components/sidebar/sidebar.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/agent-full-page/build-list/build-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/plugin-header/plugin-header.tsx, src/pages/agent-full-page/sidebar/sidebar.tsx, src/pages/agents-page/agents-table/actions-column/actions-column.tsx, src/pages/agents-page/agents-table/name-column/name-column.tsx, src/pages/service-group-full-page/service-group-header/service-group-header.tsx
=> EPMDJ-6714: Replaced push with react router Link

package-lock.json, package.json, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-6587: Update ui-kit version

src/forms/fields/field.tsx
=> EPMDJ-6897: Fix validation in fields

src/forms/form-validators.ts, src/forms/index.ts, src/modules/quality-gate-pane/quality-gate-settings/quality-gate-settings.tsx, src/modules/quality-gate-pane/quality-gate-settings/threshold-value-field/threshold-value-field.tsx
=> EPMDJ-6886: Add styles for threshold value field type number

src/components/tabs/tabs.tsx, src/pages/agent-full-page/coverage-plugin/overview/overview.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-cell/test-to-code-cell.tsx, src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
=> EPMDJ-6896: Update SG t2c cells

src/forms/form-validators.spec.ts, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-6903: Fix conditional rendering

src/components/toolbar/notifications-sidebar/notifications-sidebar.tsx, src/components/toolbar/toolbar.tsx, src/modules/breadcrumbs/breadcrumbs.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/routes/page-switcher.tsx
=> EPMDJ-6874: add routes for baseline, notification, session management

src/layouts/app-layout/app-layout.tsx, src/modules/breadcrumbs/breadcrumbs.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/agent-full-page/agent-full-page.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx, src/routes/page-switcher.tsx
Issue: EPMDJ-6908, EPMDJ-6874, EPMDJ-6918
=> EPMDJ-6908: Fix covered methods, associated tests, T2C dashboard routes

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-project-tests/scope-project-tests.tsx
=> EPMDJ-6827: The number of tests = 0 on the Active and Finish scope pages

src/common/connection/drill-socket.ts, src/notification-manager/notification-manager.tsx
=> EPMDJ-6922: add success message on socket reconnecting

src/common/connection/drill-socket.ts
=> EPMDJ-6958: information doesn`t update after reconnect to BE

src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx
=> EPMDJ-6945: Update styles in "Covered methods" pane 

src/pages/agent-full-page/plugin-header/plugin-header.tsx
=> EPMDJ-6961: disable setting button when agent is offline in Plugin header

src/modules/covered-methods-by-test-sidebar/methods-list/methods-list.tsx
=> EPMDJ-6945: Add padding in covered methods pane

src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-6964: Added checks on undefined

src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-6913: Update menu item on all scope page

src/modules/breadcrumbs/breadcrumbs.tsx, src/modules/plugins-settings-tab/plugins-settings-tab.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-6908: Update incorrect link paths

src/modules/breadcrumbs/breadcrumbs.tsx
=> EPMDJ-6925: Show all scopes link in breadcrumbs on scope page

src/components/toolbar/notifications-sidebar/notifications-sidebar.tsx, src/components/toolbar/toolbar.tsx, src/hooks/use-close-modal.ts, src/pages/agent-full-page/agent-full-page.tsx
=> EPMDJ-6930: Hide sidebar when open notification panel on all build page

src/pages/agent-full-page/agent-full-page.tsx
=> EPMDJ-7030: Add trigger mark as read when switching to a new build page

src/modules/breadcrumbs/breadcrumbs.tsx
=> EPMDJ-7031: Update t2c and dashboard routes for service group in breadcrumbs

src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-6946: Replace # with %23

src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
=> EPMDJ-7044: Update tooltips in session manager

src/pages/agent-full-page/sidebar/sidebar.tsx
=> EPMDJ-7145: Update sidebar links styles

src/pages/agent-registration-page/agent-registration-page.tsx
=> EPMDJ-7113: Redirect to plugin dashboard after registration

src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-7103: Encode testId in covered methods and associated tests panels

src/common/connection/drill-socket.ts, src/common/connection/subscribers-collection.ts
=> EPMDJ-6932: Add debounce on unsubscribe

src/components/sidebar/sidebar.tsx, src/pages/agent-full-page/sidebar/sidebar.tsx
=> EPMDJ-7145: Update sidebar links

src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-7157: Fix crash page if test has name with cyrillic symbols

src/pages/service-group-registration-page/service-group-registration-page.tsx
=> EPMDJ-7160: Redirect to plugin page if we register SG with one plugin

package.json, src/hooks/use-query.ts, src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx, src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx, src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx, src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx, src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
=> EPMDJ-7157: Covered methods pane don`t open if test name has '%' symbol

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx
=> EPMDJ-7162: Fix disabled 'unset baseline' button

src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-7165: Disable "cancel" button when scope is finishing

src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
=> EPMDJ-7163: The empty Active Scope in a duplicated tab is not deleted

src/components/table/table.tsx
=> EPMDJ-7175: Fix no display menu on "all scope" page

src/components/table/table.tsx, src/pages/agent-full-page/build-list/build-list.tsx
=> EPMDJ-7174: Fix no display baseline icon on "all builds" page

package-lock.json, package.json
=> EPMDJ-7213: Update ui-kit package version

src/pages/agents-page/agents-table/actions-column/actions-column.tsx
=> EPMDJ-7180: Fix available SG registration button when JS agent in SG

src/common/connection/subscribers-collection.ts
=> EPMDJ-7176: Drill socket can`t decrease subscribers quantity less then 0

src/pages/agent-full-page/coverage-plugin/covarage-plugin-modals.tsx, src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx, src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx, src/pages/agent-full-page/coverage-plugin/store/plugin-context.ts, src/pages/agent-full-page/coverage-plugin/store/reducer.ts, src/pages/agent-full-page/coverage-plugin/store/store-types.ts
=> EPMDJ-7244: Modals show the actual state

src/pages/settings-page/agent-settings/agent-settings.tsx
=> EPMDJ-7282: Remove unsave change modal on plugin tab

src/components/toolbar/notifications-sidebar/notification/notification.tsx, src/components/toolbar/notifications-sidebar/notifications-sidebar.tsx
=> EPMDJ-7316: Fix styles in notification panel

src/components/table/table.tsx
=> EPMDJ-7308: Fix styles in thead

src/components/wizard/wizard.tsx, src/notification-manager/notification-manager.tsx
=> EPMDJ-7334: Added that the disable status depends on the message type

src/common/connection/drill-socket.ts
=> EPMDJ-7400: Change encodeURI to encodeURIComponent in drill socket

src/common/connection/drill-socket.ts
=> EPMDJ-7400: Replace "%2F" to "/" in encoded string

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx
=> EPMDJ-7472: Add spinner to set/unset as baseline button

src/modules/system-settings-form/system-settings-form.tsx, src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.tsx, src/pages/settings-page/agent-settings/js-system-settings-form/js-system-settings-form.tsx, src/pages/settings-page/service-group-settings/service-group-general-settings-form/service-group-general-settings-form.tsx, src/utils/index.ts, src/utils/is-pristine.spec.ts, src/utils/is-pristine.ts
=> EPMDJ-7506: Don`t show "unsaved changes" modal when click to field

src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-7597: Disable submit button and not update field after backend reconnect in rename scope modal

src/pages/settings-page/service-group-settings/service-group-settings.tsx
=> EPMDJ-7282: Remove unsave change modal on plugin tab for service group

src/modules/sessions-management-pane/sessions-management-pane.tsx
=> EPMDJ-7435: show success alert to start test session in the plural for SG

src/modules/tests-to-run/tests-to-run-list/bar-chart/chart.tsx
=> EPMDJ-7744: Visually separate build with no tests to run

src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx
=> EPMDJ-7743: Update text in baseline build modal

src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
=> EPMDJ-7811: Update header text on all scopes page

src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
=> EPMDJ-7808: Update layout in modals

src/components/error-fallback/page-not-found-error-fallback.tsx, src/pages/not-found-page/not-found-page.tsx
=> EPMDJ-7178: Update 404 page layout

src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx, src/modules/quality-gate-pane/quality-gate-pane.tsx, src/modules/sessions-management-pane/actions-panel/actions-panel.tsx, src/modules/sessions-management-pane/active-sessions-list/session-info/session-info.tsx, src/modules/sessions-management-pane/operation-action-warning/operation-action-warning.tsx, src/modules/sessions-management-pane/store/reducer.ts, src/modules/sessions-management-pane/store/sessions-management-pane-context.tsx, src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/baseline-build-modal/baseline-build-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/delete-scope-modal/delete-scope-modal.tsx, src/pages/agent-full-page/coverage-plugin/scope/rename-scope-modal/rename-scope-modal.tsx
=> EPMDJ-7801: Disable "Cancel" button when has loading
